//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionReport
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int userId { get; set; }
        public string actionDescription { get; set; }
        public string origin { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
