//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentGrading
    {
        public int id { get; set; }
        public int taskId { get; set; }
        public double score { get; set; }
        public string performanceDescription { get; set; }
    
        public virtual CourseTasks CourseTasks { get; set; }
    }
}
