//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPerWeek
    {
        public int id { get; set; }
        public int weekId { get; set; }
        public string header { get; set; }
        public string content { get; set; }
    
        public virtual Weeks Weeks { get; set; }
    }
}
