//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAssignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseAssignments()
        {
            this.CourseTasks = new HashSet<CourseTasks>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string indications { get; set; }
        public System.DateTime deadline { get; set; }
        public bool active { get; set; }
        public int weekId { get; set; }
    
        public virtual Weeks Weeks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTasks> CourseTasks { get; set; }
    }
}
