//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAvailable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseAvailable()
        {
            this.CourseReport = new HashSet<CourseReport>();
            this.EnrolledCourses = new HashSet<EnrolledCourses>();
            this.Weeks = new HashSet<Weeks>();
        }
    
        public int id { get; set; }
        public int teacherId { get; set; }
        public int courseId { get; set; }
        public int scheduleId { get; set; }
        public int enrolledStudents { get; set; }
        public int durationInWeeks { get; set; }
        public bool active { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual TeacherData TeacherData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseReport> CourseReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrolledCourses> EnrolledCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weeks> Weeks { get; set; }
    }
}
