//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAvailable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseAvailable()
        {
            this.EnrolledCourses = new HashSet<EnrolledCourses>();
        }
    
        public int id { get; set; }
        public int teacherId { get; set; }
        public int courseId { get; set; }
        public int scheduleId { get; set; }
        public bool active { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual TeacherData TeacherData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrolledCourses> EnrolledCourses { get; set; }
    }
}
