//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolledCourses
    {
        public int id { get; set; }
        public int courseId { get; set; }
        public int studentId { get; set; }
    
        public virtual CourseAvailable CourseAvailable { get; set; }
        public virtual Users Users { get; set; }
    }
}
