//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEE_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorReport
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int userId { get; set; }
        public string errorDescription { get; set; }
        public string origin { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
